ByConity/byconity.github.io

- source/_posts/zh-cn/docs/基础使用手册/管理后台任务.md
- source/_posts/zh-cn/docs/高级用户手册/配置后台任务.md
当前仅CONSUMER任务支持RESTART，MERGE/GC任务不支持RESTART
> update docs about control background task

- source/_posts/zh-cn/docs/基础使用手册/监控集群.md
Correct the markdown table format of Server and TOS metric introduction.
> Correct the markdown table format

- docusaurus.config.js
The file type is png. We need to change it.
> Fixed the socail card configration error

- docs/advanced-guide/query-optimiser.mdx
Update query-optimiser in English
> Translate query-optimiser guide in English

- docs/community/git-workflow.mdx
* fixing the format issue
* using the main branch to replace the master branch.
> Polish the documentation of git workflow

- docs/basic-guide/docker-wrapper.mdx
> doc: Added phsical server docker wrapper deployment

- docs/basic-guide/foundationdb-installation.mdx
- docs/basic-guide/hdfs-installation.mdx
> doc: Added installation document of foundationdb and HDFS

- docusaurus.config.js
> Enable Google Analytics

- i18n/zh-cn/code.json
- i18n/zh-cn/docusaurus-theme-classic/footer.json
- i18n/zh-cn/docusaurus-theme-classic/navbar.json
Added the Chinese translation to the website i18n.
Close #145
> Update the website manual display into Chinese

- docs/basic-guide/cluster-configuration.mdx
- i18n/zh-cn/docusaurus-plugin-content-docs/current/basic-guide/cluster-configuration.mdx
Add s3 related configuration document
> Update s3's configuration

- docs/introduction/background-and-technical-architecture.mdx
- docs/introduction/main-principle-concepts.mdx
- docs/introduction/quick-start.mdx
Modified Background and technical architecture, and main principle concepts documents. Made English corrections and additions.
> English corrections and additions to docs

- docusaurus.config.js
> Integrate Algolia search

- docs/advanced-guide/0.2.0_s3_upgrade_checklist.mdx
Add upgrade check list for s3 storage cluster which will upgrading from s3 preview version(before 0.2.0) to late 0.2.0
> Add 0.2.0 s3 upgrade checklist

- docs/advanced-guide/0.2.0_s3_upgrade_checklist.mdx
Update docker image name from byconity/bycontiy-server to byconity/byconity
> Update docker image name

- docs/introduction/recommended-use-case.mdx
dashboard is better than "Kanban"
> [Minor]Use proper description

- docs/advanced-guide/ingest-column.mdx
Upload document for ingest column query
> Add document for ingest column query

- docs/data-import/Ad-hocs/_category_.json
- docs/data-import/Ad-hocs/ingest_column.mdx
- docs/data-import/data-import-tuning.mdx
- docs/data-import/import-methods/_category_.json
Add document for column ingestion
> Add document for column ingestion

- README.md
- community/tsc-membership.mdx
I added a section to explain the TSC vote and how to become a TSC member.
> Update the tsc membership document

- docs/query-optimization/complex-query-optimization.mdx
- i18n/zh-cn/docusaurus-plugin-content-docs/current/query-optimization/complex-query-optimization.mdx
add some query-level tune parameter descriptions to docs
> add query-level tune parameter description to docs

- docs/query-optimization/complex-query-optimization.mdx
- i18n/zh-cn/docusaurus-plugin-content-docs/current/query-optimization/complex-query-optimization.mdx
> fix query-level-tune title
